### ISSUE TITLE
Next Release?

### ISSUE THREAD

**Issue by trevorriles** [brendanhay/amazonka#406]
Can we expect a new release soon. I'm particularly interested in this PR #388.

Also is there a good method to install based on a git has using stack? Thanks!

**Comment by reactormonk** [comment]
https://docs.haskellstack.org/en/stable/faq/#i-need-to-use-a-package-or-version-of-a-package-that-is-not-available-on-hackage-what-should-i-do

**Comment by brendanhay** [comment]
I aim to get a release out sometime this week. In the meantime please see the documentation that @reactormonk helpfully linked.

As an example, your `stack.yaml` might look as follows:

```yaml
compiler:   ghc-8.0.1
resolver:   nightly-2016-08-11

flags: {}

packages:
  - location:
      git: https://github.com/brendanhay/amazonka
      commit: 68a83fa175539e890cf2b527fde37a1208dcc361
    extra-dep: true
    subdirs:
      - amazonka
      - amazonka-ecs
      - amazonka-ec2
```

Please note the use of both `extra-dep` and `subdirs` above.
